### ISSUE TITLE
Support metadata identification for items.

### ISSUE THREAD

**Issue by nikosgram** [nikosgram/gringotts#14]
Idea by [killrrkillrr](https://www.spigotmc.org/members/killrrkillrr.633320/) on spigot.org

**Comment by jaz-on** [comment]
I was just about to suggest this improvement! I am very interested in this ticket. 

One would differentiate between the gold_nugget with nbt tag used as the currency of my server and the vanilla gold_nugget.
The two versions of the gold_nugget (or any other item used as currency) would be visually different, especially since it is not possible to give an enchantment to some items without specific permissions on many servers.

I know you have a lot of things planned for Gringotts, do you have a specific date for this addition?

Thanks you for the maintenance of this essential plugin!

**Comment by nikosgram** [comment]
Implemented on latest version :) 

Config example:
```yaml
  denominations:
    - material: emerald
      value: 1
      unit-name: Emeraldo
      unit-name-plural: Emeraldos
      displayname: Emeraldo
      damage: 10
      custom_model_data: 1
      lore:
        - line1
        - line2
    - material: emerald_block
      value: 9
      unit-name: Emeralde
      unit-name-plural: Emeraldes
      displayname: Emeralde
      damage: 10
      custom_model_data: 1
      lore:
        - line1
        - line2
```
